### ISSUE TITLE
Stuck waiting for confirmation

### ISSUE THREAD

**Issue by botrosco** [anarkrypto/confirmy-block#2]
Am using a node run in docker
Seems fine until waiting for confirmation when it gets "stuck"
![image](https://user-images.githubusercontent.com/51170107/114051120-bb468c80-9884-11eb-881b-a6c00a7ea007.png)

**Comment by anarkrypto** [comment]
Unfortunately despite all the effort, sometimes some blocks are not confirmed with agility. When that happens, we can only wait

But remember to use the --sync --force --follow flags
