### ISSUE TITLE
"Add this lines to your config-node.toml" ... where?

### ISSUE THREAD

**Issue by AArnott** [anarkrypto/confirmy-block#3]
The README says to

> Add this lines to your config-node.toml

But it doesn't say what section to add it to. Should it be added to the `[node]` section?

**Comment by anarkrypto** [comment]
this configuration is only for those who want to use their own Nano node. It is inside the "Nano" folder, inside the directory configured in the docker installation script.

**Comment by AArnott** [comment]
Thanks. Yes, I have my own nano node and see the directory. 
My question though was what *section* of that file should it be added to. There are at least three in my file, and I'm guessing I should insert it into the first:

```
[node]

# Enable or disable voting. Enabling this option requires additional system resources, namely increased CPU, bandwidth and disk usage.
# type:bool
enable_voting = true

# Online weight minimum required to confirm a block.
# type:string,amount,raw
online_weight_minimum = "60000000000000000000000000000000000000"

# Percentage of votes required to confirm blocks. A value below 50 is not recommended.
# type:uint64
online_weight_quorum = 67

[node.websocket]

# WebSocket server bind address.
# type:string,ip
address = "::ffff:0.0.0.0"
# Enable or disable WebSocket server.
# type:bool
enable = true

[rpc]

# Enable or disable RPC.
# type:bool
enable = true
```

**Comment by anarkrypto** [comment]
Correct, it's in the node section. Now I quote this detail in README.md. Thanks!

[https://github.com/anarkrypto/confirmy-block/commit/2e2259230e755954f753e37abbcbf719a4f98669](url)
