### ISSUE TITLE
"enable_max_difficulty": false, yet I get "Difficulty above config limit or below publish threshold"

### ISSUE THREAD

**Issue by AArnott** [anarkrypto/confirmy-block#4]
I'm trying to help get ppl's tx confirmed.

My config.json is:
```json
{
    "node": "https://rpc.p2pow.online",
    "worker": "http://127.0.0.1:7076",
    "min_pending_amount": "0.000001",
    "enable_active_difficulty": true,
    "min_consensus": 100,
    "enable_max_difficulty": false,
    "max_difficulty_send": 100,
    "max_difficulty_receive": 6400
}
```

Yet with a command like this:

     node src/index nano_1nf3kdph1wsxkc7hqifink9n3zktfjpjbz1as434jjrp4psxpuuro7j4gpn7 --sync --follow

I end up failing with this:
```
Status Local: unconfirmed
Subtype: receive
Old multiplier: 143338.17x
Generating Work...
Difficulty above config limit or below publish threshold
```

Why am I getting this when `enable_max_difficulty` is `false`?

**Comment by anarkrypto** [comment]
First, you must use --force
But the error you're getting probably comes from your node. Install nano-work-server and set "http://[::1]:7076" as the "worker" in config.json. In the same file, set "https://rpc.p2pow.online" as a "node",
: 
you can directly download the nano-work-server binaries in "releases": https://github.com/nanocurrency/nano-work-server/releases

And run:
Linux (terminal):
./nano-work-server --gpu 0:0

Windows (CMD, prompt)
nano-work-server --gpu 0:0

**Comment by AArnott** [comment]
Thanks. How does `nano-work-server` differ from my already running node? And as my node already uses 7076 for RPC, how will that work with `nano-work-server` using the same port?

`./nano-work-server --gpu 0:0` is failing anyway. My linux env is on WSL 2. Maybe that's why?

**Comment by anarkrypto** [comment]
nano-work-server does not need to download the Nano ledger, so it is lighter. And it also has a few different settings that can solve this PoW difficulty limit problem.

If you need to use a different port, use the -l option:
./nano-work-server -l [::1]:7080 --gpu 0:0

And I don't understand about WLS, but it's possible that your GPU drivers don't work there in the same way. You can run directly on Windows.

**Comment by AArnott** [comment]
Ya, `nano-work-server` just can't access the GPU from WSL 2. But running it on Windows directly seems to be fine.
